server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://139.159.229.113:3306/circlecode_v1?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai"
    username: root
    password: root
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

huawei:
  obs:
    end-point: obs.cn-south-4.myhuaweicloud.com
    access-key: "HPUAH0VZLPSTRALKMTS6"
    secret-key: "oibodRcBnoVQk7O9LWvWDC9chN1x9IDTuHOxxhAV"
    bucket-name: codecircle
    domain-name: codecircle.obs.cn-south-4.myhuaweicloud.com

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: org.bteam.circlecode.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  secret: CodeCircleSecret
  expiration: 86400000